ClinicSystem/Areas/Admin/Models/GroupVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DataAccess.Entity;
namespace ClinicSystem.Areas.Admin.Models
{
    public class GroupVM
    {
        public List<Group> GroupListVM { get; set; }
    }
}

ClinicSystem/Areas/Admin/Models/ModuleVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DataAccess.Entity;
namespace ClinicSystem.Areas.Admin.Models
{
    public class ModuleVM
    {
        public List<Modules> ModuleList { get; set; }
    }
}

ClinicSystem/Areas/Admin/Models/UseresVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DataAccess.Entity;
namespace ClinicSystem.Areas.Admin.Models
{
    public class UseresVM
    {
        public List<Users> UserLi { get; set; }
    }
}

ClinicSystem/Areas/Admin/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Entity;
using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json;
using ClinicSystem.Areas.Admin.Models;
namespace ClinicSystem.Areas.Admin.Controllers
{
    public class GroupController : Controller
    {
        //
        // GET: /Admin/Group/
       
        public ActionResult NewGroup()
        {
            ViewBag.x = 0;
            return View("NewGroup");
        }
        
        public ActionResult New_Group(int id)
        {
            ViewBag.x=id;
            return View("NewGroup");
        }
        
        public async Task<ActionResult> GroupList()
        {
            GroupVM vm = new GroupVM();
            List<Group> GroupList = new List<Group>();
            string apiURL = "http://localhost/ClinicApi/api/Group/Fill";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(apiURL);

            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage ResponseMessage = await client.GetAsync(apiURL);
            if (ResponseMessage.IsSuccessStatusCode)
            {
                var ResponseDate = ResponseMessage.Content.ReadAsStringAsync().Result;
                GroupList = JsonConvert.DeserializeObject<List<Group>>(ResponseDate);
            }

            vm.GroupListVM = GroupList;
            return View("GroupList", vm);


        }
	}
}

ClinicSystem/Areas/Admin/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DataAccess.Entity;
using System.Net.Http;
using Newtonsoft.Json;
using ClinicSystem.Areas.Admin.Models;
namespace ClinicSystem.Areas.Admin.Controllers
{
    public class ModuleController : Controller
    {
        //
        // GET: /Admin/Module/
        [HttpGet]
        public ActionResult NewModules()
        {
            ViewBag.x = 0;
            return View();
        }
       
        public ActionResult New_Modules(int id)
        {
            ViewBag.x = id;
            return View("NewModules");
        }

        public async Task<ActionResult> ModulesList()
        {
            ModuleVM vm = new ModuleVM();
            List<Modules> modulelist = new List<Modules>();
            string apiURL = "http://localhost/ClinicApi/api/Modules/Fill";                            
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(apiURL);
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage ResponseMessage = await client.GetAsync(apiURL);

            if (ResponseMessage.IsSuccessStatusCode)
            {
                var responsedata = ResponseMessage.Content.ReadAsStringAsync().Result;
                modulelist = JsonConvert.DeserializeObject<List<Modules>>(responsedata);
                
            }
           
            vm.ModuleList = modulelist;
            return View("ModulesList",vm);
        }
        //public async Task<ActionResult> ModulesList()
        //{
        //    string name=@ViewBag.name;
        //    ModuleVM vm = new ModuleVM();
        //    List<Modules> modulelist = new List<Modules>();
        //    string apiURL = "http://localhost/ClinicApi/api/Modules/Search";
        //    HttpClient client = new HttpClient();
        //    client.BaseAddress = new Uri(apiURL);
        //    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        //    HttpResponseMessage ResponseMessage = await client.GetAsync(apiURL);

        //    if (ResponseMessage.IsSuccessStatusCode)
        //    {
        //        var responsedata = ResponseMessage.Content.ReadAsStringAsync().Result;
        //        modulelist = JsonConvert.DeserializeObject<List<Modules>>(responsedata);

        //    }

        //    vm.ModuleList = modulelist;
        //    return View("ModulesList", vm);
        //}
	}
}

ClinicSystem/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClinicSystem.Areas.Admin.Models;
using DataAccess.Entity;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
namespace ClinicSystem.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /Admin/User/
        
        public ActionResult NewUsers()
        {
            return View("NewUsers");
        }
        public ActionResult New_Users(int id)
        {
            ViewBag.x = id;
            return View("NewUsers");
        }
        public async Task<ActionResult> UsersList()
        {
            UseresVM vm=new UseresVM();
            List<Users> userlist = new List<Users>();
            string apiURL = "http://localhost/ClinicApi/api/User/FillUserList";                        
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(apiURL);
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage ResponseMessage = await client.GetAsync(apiURL);
            if (ResponseMessage.IsSuccessStatusCode)
            {
                var responseDate = ResponseMessage.Content.ReadAsStringAsync().Result;
                userlist = JsonConvert.DeserializeObject<List<Users>>(responseDate);
            }
            vm.UserLi = userlist;


            return View("UsersList",vm);
        }
	}
}

ClinicSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ClinicSystem/Areas/Admin/Views/Group/GroupList.cshtml
@model ClinicSystem.Areas.Admin.Models.GroupVM
@{
    ViewBag.Title = "GroupList";
    Layout = "~/Views/Shared/HomePage.cshtml";
}
@section Head{
    <script type="text/javascript">
        function Edit(id)
        {
            debugger;
            window.location = '@Url.Action("New_Group/id", "Group")'.replace('id', id);
        }
        function del(id)
        {
            
            debugger;
            $.ajax({
                type:'post',
                url:'/ClinicApi/api/Group/Removee/'+id,
                contentType:'application/json',
                datatType:'Json',
                data:'{}',
                success:function (){
                    debugger;
                    alert("Success")
                },
                error: function (error) {
                    debugger;
                    alert(error.responseText);
                }

            })
        }




    </script>}
@section body{
    <div class="container x_panel">
        <div class="row x_title ">
            <div class="col-lg-10 col-md-8 col-sm-8 col-xs-8">
                <h4 style="color:blue">Group</h4>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4">

                <img src="~/Images1/Icons/passed-exam.png" style="width:50px;height:50px" />
            </div>
        </div>
        <div class="row x_title">
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 ">
                <input type="checkbox" name="chkSearchGroup" />
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 ">

                <input type="text" name="txtSearchGroup" class="form-control" placeholder="Search" />
            </div>
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                <button type="button" class=" btn btn-light">
                    <span class="glyphicon glyphicon-search"></span> Search
                </button>
            </div>

        </div>


        @{
            var main = from x in Model.GroupListVM
                       select x;

        }
        @foreach (var item in main)
        { <div class="row x_title">
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                <input type="checkbox" name="chkGroup" />
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                <h5>Group Name :@item.Name Status @item.Status</h5>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-8 col-xs-8 col-lg-offset-3 col-md-offset-2 col-sm-offset-0 col-xs-offset-0 ">

                <button type="button" id="btnEdit" onclick="Edit(@item.ID)" class=" btn btn-dark">
                    <span class="glyphicon glyphicon-edit"></span> Edit
                </button>

                <button type="button" class="btn btn-danger" onclick="del(@item.ID)">
                    <span class="glyphicon glyphicon-trash"></span> Delete
                </button>

                <button type="button" class="btn btn-danger">
                    <span class="glyphicon glyphicon-plus"></span> ChangeStatus
                </button>

            </div>

        </div>


        }

    </div>
}

ClinicSystem/Areas/Admin/Views/Group/NewGroup.cshtml
@{
    ViewBag.Title = "NewGroup";
    Layout = "~/Views/Shared/HomePage.cshtml";
}
@section Head{
    
    <script type="text/javascript">


        $(document).ready(function () {
            debugger;
            var id = '@ViewBag.x';
            if (id != 0) {
                $.ajax({
                    type: 'get',
                    url: '/ClinicApi/api/Group/edit?id=' + id,
                    contentType: 'application/jason',
                    dataType: 'Json',
                    data: '{}',
                    success: function (data) {
                        debugger;
                        $("#lblName").val(data.Name);
                        $("#lblShortName").val(data.ShortName);
                        $("#btnStatus").val(data.Status);
                        $("#btnStatusDate").val(data.StatusDate);

                    },
                    error: function (error) {
                        debugger;
                        alert(error.responseText)
                    },

                })
            }
            else {

            }
            $("#btnUpdate").click(function () {
                debugger;
                var Status;
                if ($("#btnStatus").is(':checked')) {
                    Status = 1;
                }
                else {
                    Status = 0;
                }
                var data = {
                    'ID': id,
                    'Name': $("#lblName").val(),
                    'ShortName': $("#lblShortName").val(),
                    'Status': Status,

                    'StatusDate': $("#btnStatusDate").val(),
                }
                $.ajax({
                    type: 'post',
                    url: '/ClinicApi/api/Group/Update',
                    contentType: 'application/json;charset=utf-8',
                    dataType: 'Json',
                    data: JSON.stringify(data),
                    success: function (data) {
                        debugger;
                        alert("succsess");

                    },

                    error: function (error) {
                        debugger;
                        alert(error.responseText);
                    }
                })
            })

            $("#btnSave").click(function () {
                debugger;
                var info = new Object();
                info.Name = $("#lblName").val();
                info.ShortName = $("#lblShortName").val();
                //if ($("#btnStatus").is(':checked')) {
                //    return info.Status = 1;
                //}
                //else {
                //    return info.Status = 0;
                //}
                info.Status = $("#btnStatus").val();
                info.StatusDate = $("#btnStatusDate").val();

                $.ajax({
                    type: 'post',
                    url: '/ClinicApi/api/Group/InsertGro',
                    contentType: 'application/json;charset=utf-8',
                    dataType: 'Json',
                    data: JSON.stringify(info),
                    success: function (data) {
                        debugger;
                        alert("succsess");

                    },

                    error: function (error) {
                        debugger;
                        alert(error.responseText);
                    }
                })
            })

            $("#btnDiscared").click(function () {
                debugger;
                window.location = '@Url.Action("GroupList", "Group")';

            })

            
                
               
               
            })

      
</script>
    }
            @section body{
            <div class="container x_panel">
                <div class="row x_title ">
                    <div class="col-lg-8 col-md-8 col-sm-7 col-xs-7">
                        <h4 style="color:blue">New Group</h4>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-5 col-xs-5">

                        <button type="button" id="btnSave" class="btn btn-default btn-sm btn btn-success ">
                            <span class="glyphicon glyphicon-floppy-disk"></span> Save
                        </button>

                        <button type="button" id="btnDiscared" class="btn btn-default btn-sm btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span> Discared
                        </button>
                        <button type="button" id="btnUpdate" class="btn btn-default btn-sm btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span> Update
                        </button>


                    </div>
                </div>

                <div class="row x_title x_panel">
                    <div class="col-lg-4 col-md-4 col-sm-5 col-xs-5">
                        <h4>Group Information</h4>
                    </div>

                </div>
           
                <div class="row form-group">
                    <div class="col-lg-2 col-md-3 col-sm-2 col-xs-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-xs-offset-3  ">
                        <label id="lblGroupName">Name</label>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">
                        <input type="text" id="lblName" name="txtGroupName" class="form-control" />
                    </div>
                </div>
           
                <div class="row form-group">
                    <div class="col-lg-2 col-md-3 col-sm-2 col-xs-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-xs-offset-3  ">
                        <label id="lblGroupShortName">Short Name</label>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                        <input type="text" id="lblShortName" name="txtGroupShortName" class="form-control" />
                    </div>
                </div>
           
                <div class="row form-group">
                    <div class="col-lg-2 col-md-3 col-sm-2 col-xs-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-xs-offset-3  ">
                        <label id="lblGroupStatus">Status:</label>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">
                        <input type="checkbox" id="btnStatus" name="chkGroupStatus" />Active
                    </div>
                </div>
                
                <div class="row form-group">
                    <div class="col-lg-2 col-md-3 col-sm-2 col-xs-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-xs-offset-3  ">
                        <label id="lblGroupStatusDate">Status Date</label>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">

                        <div class="input-group">
                            <input type="text" id="btnStatusDate" class="form-control" name="txtGroupStatusDate">
                            <span class="input-group-addon"><i class="fa fa-calendar form-control-feedback"></i></span>
                        </div>
                    </div>
                </div>



            


                <div class="row x_title x_panel">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-lg-offset-1 col-md-offset-1 col-sm-offset-0 col-xs-offset-0">
                        <h4 style="text-align:center">Pages</h4>
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col"><input type="checkbox" name="chektableh>" /></th>
                                    <th scope="col">Page Name</th>
                                    <th scope="col">Page Order</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable>" /></th>
                                    <td>Patien tList</td>
                                    <td>1</td>
                                    <td><img src="~/Images1/Icons/add-icon-76240.png" style="width:30px;height:30px" /></td>
                                </tr>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable>" /></th>
                                    <td>New Patien</td>
                                    <td>2</td>
                                    <td><img src="~/Images1/Icons/add-icon-76240.png" style="width:30px;height:30px" /></td>
                                </tr>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable>" /></th>
                                    <td>Visit List</td>
                                    <td>1</td>
                                    <td><img src="~/Images1/Icons/add-icon-76240.png" style="width:30px;height:30px" /></td>
                                </tr>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable>" /></th>
                                    <td>New Visit</td>
                                    <td>2</td>
                                    <td><img src="~/Images1/Icons/add-icon-76240.png" style="width:30px;height:30px" /></td>
                                </tr>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable>" /></th>
                                    <td>Users</td>
                                    <td>4</td>
                                    <td><img src="~/Images1/Icons/add-icon-76240.png" style="width:30px;height:30px" /></td>
                                </tr>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable>" /></th>
                                    <td>Errors Details</td>
                                    <td>3</td>
                                    <td>
                                        <img src="~/Images1/Icons/add-icon-76240.png" style="width:30px;height:30px" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-xs-offset-3">
                        <h4 style="text-align:center">Accessed</h4>
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col"><input type="checkbox" name="chektableh2>" /> </th>
                                    <th scope="col">Page Name</th>
                                    <th scope="col">Page Order</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable2>" /></th>
                                    <td>Mark</td>
                                    <td>Otto</td>
                                    <td><img src="~/Images1/Icons/remove-icon-png-26.png" style="width:30px;height:30px" /></td>
                                </tr>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable2>" /></th>
                                    <td>Jacob</td>
                                    <td>Thornton</td>
                                    <td><img src="~/Images1/Icons/remove-icon-png-26.png" style="width:30px;height:30px" /></td>
                                </tr>
                                <tr>
                                    <th scope="row"><input type="checkbox" name="chektable2>" /></th>
                                    <td>Larry</td>
                                    <td>the Bird</td>
                                    <td>
                                        <img src="~/Images1/Icons/remove-icon-png-26.png" style="width:30px;height:30px" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>

            }

ClinicSystem/Areas/Admin/Views/Module/ModulesList.cshtml
@model ClinicSystem.Areas.Admin.Models.ModuleVM
@{
    ViewBag.Title = "ModulesList";
    Layout = "~/Views/Shared/HomePage.cshtml";
}
@section Head{
    <script type="text/javascript">
        function edit(id)
        {
            debugger;
            window.location = '@Url.Action("New_Modules/Id", "Module")'.replace('Id', id);

        }

        function del(id)
        {
            
            debugger;
            $.ajax({
                type:'post',
                url:'/ClinicApi/api/Modules/Removee/'+id,
                contentType:'application/json',
                datatType:'Json',
                data:'{}',
                success:function (){
                    debugger;
                    alert("Success")
                },
                error: function (error) {
                    debugger;
                    alert(error.responseText);
                }

            })
        }
        function Search(name)
        {
            debugger;
            var name = '@ViewBag.x';
            $.ajax({
                type: 'post',
                url: '/ClinicApi/api/Module/edit?name=' + name,
                contentType: 'application/json',
                dataType: 'Json',
                data: '{}',
                success: function (data)
                {
                    alert("")
                },
                error:function(Error)
                {
                    alert("error")
                },
            })
        }

    </script>
    }
@section body{
    <div class="container x_panel">
        <div class="row x_title">
            <div class="col-lg-11 col-md-11 col-sm-11 col-xm-11"><h4 style="color:blue">Modules List</h4></div>
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                <img src="~/Images1/Icons/passed-exam.png" />
            </div>
        </div>
        <div class="row x_title">
            <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                <input type="checkbox" name="chkSearch" />
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                <input type="text" id="txtSearch" name="txtSearch" placeholder="Search" class="form-control" />

            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">

                <button type="button" onclick="Search()" class="btn btn-light">
                    <span class="glyphicon glyphicon-search"></span> Search
                </button>
            </div>
        </div>


        @{
            var main = from x in Model.ModuleList
                       where x.SubModule == 0
                       select x;

        }
        @foreach (var ma in main)
        {
            <div class="row x_title">

                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                    <input type="checkbox" name="chkModuleName" />
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">Modules Name  @ma.Name  Order @ma.Order</div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-lg-offset-6 col-md-offset-6 col-sm-offset-6 col-xs-offset-6">
                    <button type="button" class=" btn btn-dark" id="btnEdit" onclick="edit(@ma.ID)">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>

                    <button type="button" class="btn btn-danger" onclick="del(@ma.ID)">
                        <span class="glyphicon glyphicon-trash"></span> Delete
                    </button>
                </div>
            </div>





            var sub = from b in Model.ModuleList
                      where b.SubModule == ma.ID
                      select b;
            foreach (var su in sub)
            {


                <div class="row x_title ">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-lg-offset-2 ">Sub Module: @su.Name Modules List Order: @su.Order </div>
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-4  col-lg-offset-3 col-md-offset-5 col-sm-offset-5 col-xs-offset-5">
                        <button type="button" class=" btn btn-dark">
                            <span onclick="edit(@su.ID)" class=" glyphicon glyphicon-edit"></span> Edit
                        </button>
                        <button type="button" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span> Delete
                        </button>
                    </div>
                </div>


            }



        }


        @*<div class="row x_title ">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">Sub Module: Modules List Order:1</div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4  col-lg-offset-5 col-md-offset-5 col-sm-offset-5 col-xs-offset-5">
                    <button type="button" class=" btn btn-dark">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>
                    <button type="button" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span> Delete
                    </button>
                </div>
            </div>

            <div class="row x_title ">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">Sub Module: Modules List Order:1</div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4  col-lg-offset-5 col-md-offset-5 col-sm-offset-5 col-xs-offset-5">
                    <button type="button" class=" btn btn-dark">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>
                    <button type="button" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span> Delete
                    </button>
                </div>
            </div>

            <div class="row x_title ">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">Sub Module: Modules List Order:1</div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4  col-lg-offset-5 col-md-offset-5 col-sm-offset-5 col-xs-offset-5">
                    <button type="button" class=" btn btn-dark">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>
                    <button type="button" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span> Delete
                    </button>
                </div>
            </div>

            <div class="row x_title ">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">Sub Module: Modules List Order:1</div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4  col-lg-offset-5 col-md-offset-5 col-sm-offset-5 col-xs-offset-5">
                    <button type="button" class=" btn btn-dark">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>
                    <button type="button" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span> Delete
                    </button>
                </div>
            </div>*@




    </div>












}

ClinicSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClinicSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>